import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faAngleDown } from "@fortawesome/free-solid-svg-icons";
import { lists } from "../src/constants/lists";
import TaskColumn from "../src/components/TaskColumn";
import { gql } from "@apollo/client";
import client from "../src/services/apolloService";

export default function Home({ tasks }) {
  const { container, header, title, filter, content } = styles;
  console.log(tasks);
  return (
    <div className={container}>
      <Head>
        <title>Cool Task List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={header}>
        <span className={title}>Task List</span>
        <button className={filter}>
          <span>This day</span>
          <FontAwesomeIcon className="w-6 h-4" icon={faAngleDown} />
        </button>
      </div>
      <div className={content}>
        {lists.map((x) => (
          <TaskColumn
            key={x.title}
            taskColumn={x}
            tasks={tasks.filter((y) => y.statusId === x.type)}
          ></TaskColumn>
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query GetTasks {
        tasks: tasks:t_task(order_by: { started: asc }) {
          title
          description
          statusId: status_id
          started
          closed
        }
      }
    `,
  });

  return {
    props: {
      tasks: data.tasks,
    },
  };
}
